stages:
    - build
    - test
    
build:
    stage: build
    script:
        - touch info.txt
    artifacts:
        paths:
            - info.txt

test:
    stage: test
    script:
        - test -f info.txt